### ISSUE TITLE
Request for more examples / libs /docs

### ISSUE THREAD

**Issue by CptHolzschnauz** [telit/arduino-me310-library#6]
Charlie is a very interesting board you made! Is it possible to provide some basic examples like the sendSMS sketch from the MKRNB examples to answer the basic questions and to find an entry point.
Is there any general arduino lib like MKRNB for the SARA-410?
What about adapting the MKRNB lib to the Telit modem?
Because of the flaky behaviour of the SARA-410 i (And a lot more frustrated coders) are looking for a alternative like you built!
All we need is software...

**Comment by fabiopi-tlt** [comment]
Hello, we will look into it, we plan to add new examples for sure, an SMS one will be good as well

**Comment by fabiopi-tlt** [comment]
hello, we released the first version of a MKRNB -like library: https://github.com/telit/arduino-tlt-library 
we plan to add also GNSS management in the near future

**Comment by CptHolzschnauz** [comment]
Wow, very nice. There are a lot frustrated u-blox fighters around. I will check it out as soon as i get my charlie.
Question: Are the Telit full LTE  modem pin compatible with the charlie PCB? 
If so, it would be very nice to release a full LTE version with I2S connected (As arduino did with the mkr 1400)
To change a pin compatible modem on the charlie must be easy and cheap.
At the moment there is no full LTE MKR form factor board on the market. The reality with LTE-M and NB IoT is that the carriers or the ground stations simply are not ready. 
The absolute best would be a LTE 1 or 4 with 3G fallback on a charlie board....
